// src/app/layout.tsx
import './globals.css';
import { SpeedInsights } from "@vercel/speed-insights/next"
import Sidebar from '@/components/ThemeBuilder/02-Sidebar';
import Footer from '@/components/ThemeBuilder/04-Footer';

export const metadata = {
  title: "Kensen University",
  description: "Generated by Aslam",
  icon: "/images/KensenLogoRound.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#1c2431]">
        <div className="layout-container">
          <Sidebar />
          <main>{children}</main>
          <SpeedInsights />
          <Footer />
        </div>
      </body>
    </html>
  );
}
