import Head from 'next/head'
import React from 'react'
import Layout from '@/app/layout' // Import RootLayout jika diperlukan, tetapi biasanya ini tidak diperlukan di sini
import TableSiswa from '@/components/Pages/DashboardPage/TableSiswa'

export default function DashboardPage() {
    return (
        <>
            <Head>
                <title>Universitas Kensen</title>
                <meta name="description" content="Generated by Create Next Stack." />
            </Head>
            <main>
                {/* Konten dashboard */}
                <div className="w-full lg:ps-64 overflow-x-auto bg-[#1c2431]">
                    <div className="p-4 lg:p-10 mt-5 lg:mt-0">
                        <div className="border-b-2 border-[#ffffff3b] my-10"></div>
                            <TableSiswa/>
                    </div>
                </div>
            </main>
        </>
    )
}
